"""create initial database schema

Revision ID: afff41ccf430
Revises: 
Create Date: 2026-09-23 07:14:15.657548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afff41ccf430'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('client_version', sa.Integer(), nullable=True),
    sa.Column('server_version', sa.Integer(), nullable=False),
    sa.Column('client_payload', sa.JSON(), nullable=False),
    sa.Column('server_payload', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_operation_id'), 'conflicts', ['operation_id'], unique=False)
    op.create_index(op.f('ix_conflicts_record_id'), 'conflicts', ['record_id'], unique=False)
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    op.create_table('sync_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_status', sa.String(length=20), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_history_operation_id'), 'sync_history', ['operation_id'], unique=False)
    op.create_index(op.f('ix_sync_history_record_id'), 'sync_history', ['record_id'], unique=False)
    op.create_index(op.f('ix_sync_history_status'), 'sync_history', ['status'], unique=False)
    op.create_index(op.f('ix_sync_history_sync_id'), 'sync_history', ['sync_id'], unique=True)
    op.create_index(op.f('ix_sync_history_timestamp'), 'sync_history', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('local_sync_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_details', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_sync_operations_operation_id'), 'local_sync_operations', ['operation_id'], unique=True)
    op.create_index(op.f('ix_local_sync_operations_record_id'), 'local_sync_operations', ['record_id'], unique=False)
    op.create_index(op.f('ix_local_sync_operations_status'), 'local_sync_operations', ['status'], unique=False)
    op.create_index(op.f('ix_local_sync_operations_user_id'), 'local_sync_operations', ['user_id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_created_by'), 'records', ['created_by'], unique=False)
    op.create_index(op.f('ix_records_status'), 'records', ['status'], unique=False)
    op.create_index(op.f('ix_records_title'), 'records', ['title'], unique=False)
    op.create_index(op.f('ix_records_updated_at'), 'records', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_updated_at'), table_name='records')
    op.drop_index(op.f('ix_records_title'), table_name='records')
    op.drop_index(op.f('ix_records_status'), table_name='records')
    op.drop_index(op.f('ix_records_created_by'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_local_sync_operations_user_id'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_status'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_record_id'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_operation_id'), table_name='local_sync_operations')
    op.drop_table('local_sync_operations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_history_timestamp'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_sync_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_status'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_record_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_operation_id'), table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_record_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_operation_id'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
